title: <p align="center"> Dhruva Handa </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="docs/Dhruva_Handa.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dhruva-handa/">LinkedIn</a> |
  <a href="https://github.com/DhruvaHanda">GitHub</a>
  
  <br>   
  Proficiency in customer success is a hallmark of my approach, where I integrate data analysis and CRM to amplify 
  client engagement and foster business growth. Our collaborative efforts in Python, SQL, and 
  visualization tools have been essential in upholding data integrity and advancing actionable 
  strategies for our clients.
  <br>
  </p>

theme: jekyll-theme-minimal
